#!/usr/bin/python


# Calculating Protein Mass
# http://rosalind.info/problems/prtm/

# Global weight dictionary
weightDict = {"A" : 71.03711,
                "C" : 103.00919,
                "D" : 115.02694,
                "E" : 129.04259,
                "F" : 147.06841,
                "G" : 57.02146,
                "H" : 137.05891,
                "I" : 113.08406,
                "K" : 128.09496,
                "L" : 113.08406,
                "M" : 131.04049,
                "N" : 114.04293,
                "P" : 97.05276,
                "Q" : 128.05858,
                "R" : 156.10111,
                "S" : 87.03203,
                "T" : 101.04768,
                "V" : 99.06841,
                "W" : 186.07931,
                "Y" : 163.06333 }


def calculateMass(inStr):
    # Helper variable ininitalize mass with 0
    mass = 0

    # Iterate over each character in inStr
    for c in inStr:
        # Iterate over key an values in dictionary
        for k, v in weightDict.items():
            # Compare character with dictionary
            if c == k:
                # Add value to mass 
                mass += v

    # Return mass with round to 4 
    return round(mass, 4)
        
inStr = "CCWCNHVLMMCCIAYIGFASVNSNDTHQMNDYEFAWKHKHGVFEKTSHSDAHMFKWQECHERDCNQTFHWLQNHSNFLIRVKISWMTATSPYMKFDFFYENMIWVHSPQHDTRSALYPNHACKVEVECHCARQLYANKEFCWPACYKPILWYLQRNLKSQCRGIATEPCGNAVDSANYYEGLCKFPKVKFQEKYLTCDEQKFLMILQTNPHHFALLHLGQMARSDTTRESEIGRVEGTTSIQESIPGWIEKSEWLFVNWLNIRMPQTLLRKKLIHIFECDEPEIAMVTQVIACYSQMICDYCLSIIDFWDVHAWNVVYYKYAGPNMFYHKRNTSWKIAAESSLWHFMCNIRFMYHHEVITHLKLETKGQHSRFRVEDYIKAMVSMTSRKTDTRWCASIWKFWLMGHTNSCLLYVHLQVDLGQPVYEERSYVNCHNITTPHECNTGIDLMLQSWPTQVHFQHINLGISLPADWLNSGTDTPRSFNVFNKWLNDFSPNPALRDWEAVWWNDYAKQIAICPTRHHTPWEISHAVLLINFDPDAAFCHSLKDSCCACQDMVYQRNKIQNVHDKCEMGQTQDNWQTVLVSATVSATPVYNRMHGDRACQGETCWVYDMMKWIAFMYHGIYLQVLCPWAMLHDSMWHTTGTTHDMINISRQYCNTQSSDSKQEQFHDRDDDMYKDPIVTLLEFQKGIFQWDFVHYELQWFDNKRFFPCINHEGKQVDVKKSKRPLLKFQHCKQSYCGLWHWIYMHHYWAENTLFHTPENGFAFCYTNQNRHHGNSEDVWDDHSFKKNCCLQGHSCLLYERSRRCFMNRGAQCKLKMSAKEGGVASPRGQEDEHLKTLNPKRIVDKASYEDCFDCSTFLGMCNSHNCSLCQA"
print calculateMass(inStr)
